---
version: '3.2'

services:
  empms-es:
    build:
      context: elasticsearch/
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: elastic
    networks:
      - ot-microservices

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://empms-es:9200"]'
      ELASTICSEARCH_SERVICEACCOUNTTOKEN: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYToxa0pGUEs3WVRINmQwaG5JZ29NN21n
    depends_on:
      - empms-es
    networks:
      - ot-microservices

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.4.3
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.rum.allow_origins=["*"]
        -E setup.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["empms-es:9200"]
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=elastic
    depends_on:
      - empms-es
    networks:
      - ot-microservices

  empms-db:
    build:
      context: mysql/
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "attendance_db"
    networks:
      - ot-microservices

  empms-attendance:
    build:
      context: attendance/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.empms-attendance.rule=Host(`ot-microservices.opstree.com`) && PathPrefix(`/attendance/`)"
    volumes:
      - type: bind
        source: ./attendance/config.yaml
        target: /app/config.yaml
        read_only: true
    environment:
      CONFIG_FILE: "/app/config.yaml"
      ELASTIC_APM_SERVICE_NAME: "attendance"
      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
    networks:
      - ot-microservices
    depends_on:
      - empms-db

  empms-salary:
    build:
      context: salary/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.empms-salary.rule=Host(`ot-microservices.opstree.com`) && PathPrefix(`/salary/`)"
    environment:
      ELASTIC_APM_SERVICE_NAME: "salary"
      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
      SPRING_ELASTICSEARCH_REST_URIS: "empms-es:9200"
      SPRING_ELASTICSEARCH_REST_USERNAME: elastic
      SPRING_ELASTICSEARCH_REST_PASSWORD: elastic
    networks:
      - ot-microservices
    depends_on:
      - empms-es

  empms-employee:
    build:
      context: employee/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.empms-employee.rule=Host(`ot-microservices.opstree.com`) && PathPrefix(`/employee/`)"
    volumes:
      - type: bind
        source: ./employee/config.yaml
        target: /app/config.yaml
        read_only: true
    environment:
      CONFIG_FILE: "/app/config.yaml"
      ELASTIC_APM_SERVICE_NAME: "employee"
      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
    networks:
      - ot-microservices
    depends_on:
      - empms-es

  empms-frontend:
    build:
      context: frontend/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.empms-frontend.rule=Host(`ot-microservices.opstree.com`) && PathPrefix(`/`)"
      - "traefik.http.services.empms-frontend.loadbalancer.server.port=3000"
    networks:
      - ot-microservices

  empms-traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - empms-frontend
      - empms-attendance
      - empms-salary
      - empms-employee
    networks:
      - ot-microservices

networks:
  ot-microservices:
    driver: bridge

volumes:
  elasticsearch:
  mysql:
