spring:
  profiles: default

zuul:
  routes:
    employee:
      path: /employee/**
      url: http://172.17.0.3:8080/employee
      service-id: /employee/**

    attendance:
      path: /attendance/**
      url: http://172.17.0.3:8081/attendance
      service-id: /attendance/**

    salary:
      path: /salary/**
      url: http://172.17.0.3:8082/salary
      service-id: /salary/**
